name: 📦 Pull Request
description: 기능 추가, 버그 수정 등 작업 내용을 공유해주세요.
title: "[PR] "
labels: []
body:
  - type: dropdown
    id: pr_type
    attributes:
      label: PR 유형
      description: 어떤 종류의 작업인가요?
      options:
        - ✨ 기능 추가 (Feature)
        - 🐞 버그 수정 (Bug Fix)
        - 🚀 배포 관련 (Deploy)
        - 🛠️ 리팩토링 (Refactor)
        - 기타 (Other)
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 작업 개요
      description: 어떤 작업을 했는지 간단히 설명해주세요.
      placeholder: 예) 로그인 오류 수정, 사용자 프로필 기능 추가 등
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 상세 내용
      description: 구현 내용, 주요 변경 사항 등을 자유롭게 작성해주세요.
      placeholder: 어떤 파일이 변경되었고, 어떤 흐름인지 작성해주세요.

  - type: textarea
    id: checklist
    attributes:
      label: 체크리스트
      description: 아래 항목을 참고하여 해당하는 항목은 완료 체크해주세요.
      placeholder: |
        - [ ] ‼️PR base repository 확인 ‼️
        - [ ] 정상 동작 확인
        - [ ] 불필요한 코드(주석, 이전 코드 등) 제거
        - [ ] 문서 업데이트 (해당 시)

  - type: input
    id: related_issues
    attributes:
      label: 관련 이슈
      description: 관련된 이슈 번호를 적어주세요.
      placeholder: closes #

  - type: textarea
    id: etc
    attributes:
      label: 기타
      description: 리뷰어에게 남기고 싶은 말이나 참고 사항이 있다면 작성해주세요.
      placeholder: 예) 성능 관련 부분이라 꼭 테스트 부탁드려요!