name: CD

on:
  push:
    branches: [ release ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # application.yml은 Github Secret에 올리기
      - name: Generate application.yml
        env:
          APP_CONFIG: ${{ secrets.APPLICATION_YML }}
        run: |
          mkdir -p config
          echo "$APP_CONFIG" > src/main/resources/application.yml

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Build JAR
        run: ./gradlew clean bootJar

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/glue-be:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/glue-be:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            BACKUP_DIR=/home/ec2-user/db_backups
            mkdir -p $BACKUP_DIR

            CONTAINER_ID=$(docker ps -q --filter "name=glue-be")

            if [ -n "$CONTAINER_ID" ]; then
              echo "ongoing: $BACKUP_DIR/mydb-$(date +'%Y%m%d%H%M%S').db"
              docker cp $CONTAINER_ID:/app/data/mydb.db \
                $BACKUP_DIR/mydb-$(date +'%Y%m%d%H%M%S').db
            else
              echo "no running glue container, skip backup"
            fi

            if [ -n "$CONTAINER_ID" ]; then
              docker stop $CONTAINER_ID
              docker rm   $CONTAINER_ID
            fi
            docker rm -f glue-be || true

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/glue-be:latest
            docker run -d \
              --name glue-be \
              --network redis-network \
              -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e REDIS_HOST=redis-server \
              ${{ secrets.DOCKERHUB_USERNAME }}/glue-be:latest
